### ISSUE TITLE
Build homepage UI in walmart style

### ISSUE THREAD

**Issue by thedevsouvik** [thedevsouvik/store#8]
> looks bad.
> for homepage get inspiration from **walmart** 

 _Originally posted by @thedevsouvik in [#3](https://github.com/thedevsouvik/store/issues/3#issuecomment-1985143644)_

## Tasks
- [ ] create multiple responsive cards for dashboard looking herosection (walmart design)
- [ ] build products group sections with mini product cards
- [ ] create sub featured group with mini product cards  section
- [ ] create sub dashboard style cards
